version: '3'
services:

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db_super_wallet
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  super-wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: super-wallet-app
    ports:
      - "4000"
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=db_super_wallet
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - FIREBASE_BUCKETNAME=super-wallet-app-71352.appspot.com
      - FIREBASE_JSON_PATH=target/super-wallet-0.0.1-SNAPSHOT.jar
      - PORT=4000
    depends_on:
      - postgresql

volumes:
  postgresql-data:
